import Foundation

/// Maccy-parity privacy filter for clipboard ingestion (handoff §11).
///
/// Non-negotiable: never store pasteboard content marked concealed/transient
/// (password managers, OTP apps). Types are UTI / pasteboard type strings —
/// no AppKit dependency so the gate is unit-testable in SummonCore.
public enum PasteboardPrivacy {
    /// Standard privacy type identifiers (Maccy / nspasteboard.org convention).
    public static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "com.apple.is-remote-clipboard",
        "com.typeit4me.clipping", // TypeIt4Me transient
    ]

    /// Returns true if this pasteboard change must **not** be stored.
    public static func shouldSkip(types: [String]) -> Bool {
        let set = Set(types)
        if !set.isDisjoint(with: concealedTypes) {
            return true
        }
        // Empty type list is not storable content.
        if types.isEmpty {
            return true
        }
        return false
    }

    /// Prefer plain text; reject if only private types present.
    public static func isStorableText(types: [String], hasString: Bool) -> Bool {
        guard hasString else { return false }
        return !shouldSkip(types: types)
    }

    /// Strip HTML tags / common entities and NFC-normalize for paste-as-plain.
    public static func asPlainText(_ raw: String) -> String {
        var s = raw
        if s.contains("<") {
            s = s.replacingOccurrences(
                of: #"<[^>]+>"#,
                with: "",
                options: .regularExpression
            )
        }
        // Crude RTF control word strip (`\word` / `{\…}`)
        if s.contains("\\") && (s.hasPrefix("{") || s.contains("\\rtf")) {
            s = s.replacingOccurrences(
                of: #"\\[a-zA-Z]+-?\d*[ ]?"#,
                with: "",
                options: .regularExpression
            )
            s = s.replacingOccurrences(of: "{", with: "")
            s = s.replacingOccurrences(of: "}", with: "")
        }
        let entities: [(String, String)] = [
            ("&nbsp;", " "),
            ("&amp;", "&"),
            ("&lt;", "<"),
            ("&gt;", ">"),
            ("&quot;", "\""),
            ("&#39;", "'"),
        ]
        for (e, r) in entities {
            s = s.replacingOccurrences(of: e, with: r)
        }
        return s.precomposedStringWithCanonicalMapping
            .replacingOccurrences(of: "\u{00A0}", with: " ")
    }
}
