import Foundation

/// Maccy-parity privacy filter for clipboard ingestion (handoff §11).
///
/// Non-negotiable: never store pasteboard content marked concealed/transient
/// (password managers, OTP apps). Types are UTI / pasteboard type strings —
/// no AppKit dependency so the gate is unit-testable in SummonCore.
public enum PasteboardPrivacy {
    /// Standard privacy type identifiers (Maccy / nspasteboard.org convention).
    public static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "com.apple.is-remote-clipboard",
        "com.typeit4me.clipping", // TypeIt4Me transient
    ]

    /// Returns true if this pasteboard change must **not** be stored.
    public static func shouldSkip(types: [String]) -> Bool {
        let set = Set(types)
        if !set.isDisjoint(with: concealedTypes) {
            return true
        }
        // Empty type list is not storable content.
        if types.isEmpty {
            return true
        }
        return false
    }

    /// Prefer plain text; reject if only private types present.
    public static func isStorableText(types: [String], hasString: Bool) -> Bool {
        guard hasString else { return false }
        return !shouldSkip(types: types)
    }
}
