#!/usr/bin/env bash
# Exercise a local Homebrew cask against a just-built ad-hoc Summon.app zip.
# Does not require Developer ID. Requires `brew`.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

if ! command -v brew >/dev/null 2>&1; then
  echo "cask-local: brew not found — install Homebrew first" >&2
  exit 1
fi

VERSION="${SUMMON_VERSION:-0.3.0}"
DIST="$ROOT/dist"
ZIP="$DIST/Summon-${VERSION}.zip"
# Homebrew requires casks to live in a tap under Library/Taps.
TAP_USER="naklitechie"
TAP_REPO="homebrew-summon-local"
TAP_PATH="$(brew --repository)/Library/Taps/${TAP_USER}/${TAP_REPO}"
CASK_OUT="$TAP_PATH/Casks/summon.rb"

echo "cask-local: build app"
bash "$ROOT/packaging/macos/build-app.sh"

echo "cask-local: zip app"
mkdir -p "$DIST"
rm -f "$ZIP"
( cd "$DIST" && ditto -c -k --sequesterRsrc --keepParent "Summon.app" "Summon-${VERSION}.zip" )
SHA="$(shasum -a 256 "$ZIP" | awk '{print $1}')"
FILE_URL="file://${ZIP}"

echo "cask-local: ensure local tap at $TAP_PATH"
mkdir -p "$TAP_PATH/Casks"
# Minimal tap structure Homebrew accepts
if [[ ! -f "$TAP_PATH/README.md" ]]; then
  cat > "$TAP_PATH/README.md" <<EOF
# homebrew-summon-local

Ephemeral local tap for Summon cask dry-runs (\`make cask-local\`).
Not the public \`naklitechie/homebrew-tap\`.
EOF
fi

echo "cask-local: write cask (sha256=$SHA)"
python3 - "$VERSION" "$SHA" "$FILE_URL" "$CASK_OUT" <<'PY'
import sys
version, sha, url, out = sys.argv[1:5]
body = f'''# frozen_string_literal: true

# AUTO-GENERATED by make cask-local — template: packaging/homebrew/Casks/summon.rb
cask "summon" do
  version "{version}"
  sha256 "{sha}"

  url "{url}"
  name "Summon"
  desc "Sovereign native launcher — no account, no server, no telemetry"
  homepage "https://github.com/NakliTechie/summon"

  depends_on macos: :sonoma

  app "Summon.app"

  zap trash: [
    "~/Library/Application Support/Summon",
    "~/Library/Preferences/tech.nakli.Summon.plist",
  ]
end
'''
open(out, "w").write(body)
print("wrote", out)
PY

# Also keep a copy under dist for inspection
mkdir -p "$DIST/local-tap/Casks"
cp "$CASK_OUT" "$DIST/local-tap/Casks/summon.rb"

echo "cask-local: brew style (best-effort)"
brew style --cask "${TAP_USER}/summon-local/summon" 2>/dev/null \
  || brew style "$CASK_OUT" 2>/dev/null \
  || echo "cask-local: brew style skipped — continuing"

echo "cask-local: uninstall prior test install if present"
brew uninstall --cask summon 2>/dev/null || true

echo "cask-local: install naklitechie/summon-local/summon"
HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask --force "${TAP_USER}/summon-local/summon"

echo "cask-local: assert app present"
if [[ -d "/Applications/Summon.app" ]]; then
  APP_PATH="/Applications/Summon.app"
elif [[ -d "${HOME}/Applications/Summon.app" ]]; then
  APP_PATH="${HOME}/Applications/Summon.app"
else
  echo "cask-local: Summon.app not found under /Applications" >&2
  exit 1
fi
test -x "$APP_PATH/Contents/MacOS/summon-app"
echo "cask-local: installed at $APP_PATH"

echo "cask-local: ok"
echo "cask-local: uninstall: brew uninstall --cask summon"
echo "cask-local: remove tap: rm -rf $TAP_PATH"
